_target_: src.model.edsr.EDSRLarge
scale: 4  # upscaling factor
in_ch: 3
out_ch: 3
nf: 256   # number of features (large model)
nb: 32    # number of residual blocks (large model)
res_scale: 0.1  # residual scaling factor