_target_: src.model.edsr_lite.EDSRLite
in_ch: 3
out_ch: 3
nf: 64
nb: 12
res_scale: 0.1
# mode: pre_upsample | post_upsample
mode: post_upsample
# method depends on mode:
#   pre_upsample:  learnable | bicubic
#   post_upsample: deconvolution | pixelshuffle
method: pixelshuffle
