_target_: src.model.srcnn.SRCNNPlusPlus
in_ch: 3
out_ch: 3
n1: 64  # filters in first layer
n2: 32  # filters in second layer
n3: 16  # filters in third layer
use_residual: true  # enable residual connection